//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3643
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLBanHang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn không?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới(F3).
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát(ESC).
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa(F8).
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận(F4).
        /// </summary>
        internal static string btnDraft {
            get {
                return ResourceManager.GetString("btnDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa(F6).
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết(F7).
        /// </summary>
        internal static string btnInfor {
            get {
                return ResourceManager.GetString("btnInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới(F5).
        /// </summary>
        internal static string btnLamMoi {
            get {
                return ResourceManager.GetString("btnLamMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In phiếu chi(F12).
        /// </summary>
        internal static string btnLapPhieuChi {
            get {
                return ResourceManager.GetString("btnLapPhieuChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In phiếu thu(F12).
        /// </summary>
        internal static string btnLapPhieuThu {
            get {
                return ResourceManager.GetString("btnLapPhieuThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In phiếu(F12).
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật(F2).
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc(F9).
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật thành công.
        /// </summary>
        internal static string CapNhatThanhCong {
            get {
                return ResourceManager.GetString("CapNhatThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string CaptionColumnKho {
            get {
                return ResourceManager.GetString("CaptionColumnKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string CaptionColumnMaSanPham {
            get {
                return ResourceManager.GetString("CaptionColumnMaSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập.
        /// </summary>
        internal static string CaptionColumnNhap {
            get {
                return ResourceManager.GetString("CaptionColumnNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Sản Phẩm.
        /// </summary>
        internal static string CaptionColumnTenSanPham {
            get {
                return ResourceManager.GetString("CaptionColumnTenSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ này không hợp lệ.
        /// </summary>
        internal static string DiaChiKhongHopLe {
            get {
                return ResourceManager.GetString("DiaChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu báo cáo.
        /// </summary>
        internal static string DuLieuBaoCaoKhongCo {
            get {
                return ResourceManager.GetString("DuLieuBaoCaoKhongCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập kho.
        /// </summary>
        internal static string KhoChuaNhap {
            get {
                return ResourceManager.GetString("KhoChuaNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập ký hiệu hóa đơn.
        /// </summary>
        internal static string KyHieuHoaDonChuNhap {
            get {
                return ResourceManager.GetString("KyHieuHoaDonChuNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ ký hiệu hóa đơn và seri này đã được sử dụng.
        /// </summary>
        internal static string KyHieuHoaDonDaDung {
            get {
                return ResourceManager.GetString("KyHieuHoaDonDaDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập ký tự đầu seri.
        /// </summary>
        internal static string KyTuDauSeriChuaNhap {
            get {
                return ResourceManager.GetString("KyTuDauSeriChuaNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã này đã được sử dụng.
        /// </summary>
        internal static string MaDaDung {
            get {
                return ResourceManager.GetString("MaDaDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập nhóm đối tượng.
        /// </summary>
        internal static string NhomDoiTuongChuaNhap {
            get {
                return ResourceManager.GetString("NhomDoiTuongChuaNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số SiteNumber này không hợp lệ.
        /// </summary>
        internal static string SiteNumberKhongHopLe {
            get {
                return ResourceManager.GetString("SiteNumberKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhập vào đã lớn hơn số lượng được khai báo.
        /// </summary>
        internal static string SoLuongLonHon {
            get {
                return ResourceManager.GetString("SoLuongLonHon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập số phiếu.
        /// </summary>
        internal static string SoPhieuChuaNhap {
            get {
                return ResourceManager.GetString("SoPhieuChuaNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu này đã được sử dụng.
        /// </summary>
        internal static string SoPhieuDaDung {
            get {
                return ResourceManager.GetString("SoPhieuDaDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên này đã được sử dụng.
        /// </summary>
        internal static string TenDaDung {
            get {
                return ResourceManager.GetString("TenDaDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên đối tượng.
        /// </summary>
        internal static string TenDoiTuongChuaNhap {
            get {
                return ResourceManager.GetString("TenDoiTuongChuaNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string ThongBaoTitle {
            get {
                return ResourceManager.GetString("ThongBaoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string WaringTitle {
            get {
                return ResourceManager.GetString("WaringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa thành công.
        /// </summary>
        internal static string XoaThanhCong {
            get {
                return ResourceManager.GetString("XoaThanhCong", resourceCulture);
            }
        }
    }
}
